language: node_js
node_js:
  - "10"
install:
  - yarn
#before_script:
#  # Install Webpack version
#  - if [[ -n "$WEBPACK_VERSION" ]]; then npm install --no-save webpack@$WEBPACK_VERSION; fi
#branches:
#  except:
#    - gh-pages
stages:
  - lint
  - test
  - build
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - yarn lint
    - stage: test
      script:
        # Run tests
        - yarn test:unit
    - stage: build
      script:
        - yarn build