dist: trusty
language: node_js
node_js:
  - "10"
install:
  - yarn
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
#before_script:
#  # Install Webpack version
#  - if [[ -n "$WEBPACK_VERSION" ]]; then npm install --no-save webpack@$WEBPACK_VERSION; fi
#branches:
#  except:
#    - gh-pages
stages:
  - lint
  - test
  - build
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - yarn lint
    - stage: test
      script:
        # Run tests
        - yarn test:unit
        - yarn test:e2e
    - stage: build
      script:
        - yarn build